#!/bin/sh
set -e

DSC=$1
shift
CHOWN_ID=$(stat -c "%u:%g" ${DSC})

if [ "x${DSC}" = "x" ]; then
    echo "Missing DSC argument"
    exit 1
fi

WORKDIR=$(dirname ${DSC})
cd ${WORKDIR}

finish() {
    if [ -e /build/build/ ]; then
        rm -rf /build/build/
    fi
}
trap finish EXIT

# drop privs
dpkg-source -x ${DSC} build
cd build
mk-build-deps -r -i -t "apt-get -y --no-install-recommends"
dpkg-buildpackage $@
cd ..
rm -rf build
chown ${CHOWN_ID} *
